version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: HOUSE_PLANTS
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"